id: P20F2BA42
initial_creation_type: input
source_metadata:
  title: Acala Series
  language: en
  description: 'Texts related to Acala (mi g.yo ba), the ‘Immovable One’, a wrathful
    deity who is also known as Caṇḍamahāroṣaṇa:'
  volume:
    dc2cbf6005be4225bc79fa4aac1d8de9:
      title: Acala Sādhana
      parent: Sādhanas
created_at: '2022-03-01T02:29:53.995037'
last_modified_at: '2022-03-01T02:29:53.995043'
